[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

# Force specific MIME types for JavaScript files
[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "*.mjs"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "*.jsx"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"
    X-Content-Type-Options = "nosniff"

# CSS files
[[headers]]
  for = "/assets/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"
    Cache-Control = "public, max-age=31536000"

# HTML files
[[headers]]
  for = "*.html"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false